services:
  bug-app:
    build: .
    command: sh -c "rm -f /app/tmp/pids/server.pid && rails db:create && rails db:migrate && rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - ./storage:/app/storage
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true