services:
  web:
    build: .
    command: sh -c "rails db:create && rails db:migrate && rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - ./storage:/app/storage
    ports:
      - "3000:3000"
